function update_init_options(obj)

try 
    close(obj.gui.h_options); 
end
temp = get(obj.gui.fig_main, 'position'); 
H = 400; 
W = 260; 
h_options = figure('position', [temp(1)+temp(3)+10, temp(2)+temp(4)-H, 260, H], ...
    'toolbar', 'none'); 

w1 = 150;
w2 = 100; 
h = 30; 

%% clear results or not 
pos_0 = [10, 400-1.5*h, w1, h*0.9]; 
pos_1 = [20+w1, 400-1.5*h, w2, h*0.9]; 

text_clear_results = uicontrol('parent', h_options, 'style', 'pushbutton', ...
    'unit', 'pixels', 'position', pos_0, 'string', 'clear results', ...
    'fontweight', 'bold', 'backgroundcolor', 'cyan'); 
popup_clear_results = uicontrol('parent', h_options, 'style', 'popup', ...
    'unit', 'pixels', 'position', pos_1-2, 'string', {'true', 'false'}, ...
    'fontweight', 'bold', 'value', 2-obj.options_init.clear_results, 'callback', ...
    'v=get(gco, ''value''); ease.options_init.clear_results=(v==1);'); 
%% show image 
pos_0(2) = pos_0(2) - h; 
pos_1(2) = pos_1(2) -h;  
text_show_images = uicontrol('parent', h_options, 'style', 'pushbutton', ...
    'unit', 'pixels', 'position', pos_0, 'string', 'show initialization', ...
    'fontweight', 'bold', 'backgroundcolor', 'cyan'); 
popup_show = uicontrol('parent', h_options, 'style', 'popup', ...
    'unit', 'pixels', 'position', pos_1-2, 'string', {'true', 'false'}, ...
    'fontweight', 'bold', 'value', 2-obj.options_init.show_fig, 'callback', ...
    'v=get(gco, ''value''); ease.options_init.show_fig=(v==1);'); 

%% save image 
pos_0(2) = pos_0(2) - h; 
pos_1(2) = pos_1(2) -h;  
text_save_images = uicontrol('parent', h_options, 'style', 'pushbutton', ...
    'unit', 'pixels', 'position', pos_0, 'string', 'save figures', ...
    'fontweight', 'bold', 'backgroundcolor', 'cyan'); 
popup_save = uicontrol('parent', h_options, 'style', 'popup', ...
    'unit', 'pixels', 'position', pos_1-2, 'string', {'true', 'false'}, ...
    'fontweight', 'bold', 'value', 2-obj.options_init.save_fig, 'callback', ...
    'v=get(gco, ''value''); ease.options_init.save_fig=(v==1);'); 

%% initialization method 
pos_0(2) = pos_0(2) - h; 
pos_1(2) = pos_1(2) -h; 
text_init_method = uicontrol('parent', h_options, 'style', 'pushbutton', ...
    'unit', 'pixels', 'position', pos_0, 'string', 'init. method', ...
    'fontweight', 'bold', 'backgroundcolor', 'cyan');
switch lower(obj.options_init.init_method)
    case  'tf'
        tmp_v = 1; 
    case 'semi-nmf'
        tmp_v = 2; 
end
popup_init_method_ = uicontrol('parent', h_options, 'style', 'popup', ...
    'unit', 'pixels', 'position', pos_1-2, 'string', {'TF', 'semi-NMF'}, ...
    'fontweight', 'bold', 'value', tmp_v, 'callback',...
    'temp=get(gco, ''string''); v=get(gco, ''value''); ease.options_init.init_method=temp{v};'); 

%% order statistics 
pos_0(2) = pos_0(2) - h; 
pos_1(2) = pos_1(2) -h;  
text_order_statistics = uicontrol('parent', h_options, 'style', 'pushbutton', ...
    'unit', 'pixels', 'position', pos_0, 'string', 'order statistics', ...
    'fontweight', 'bold', 'backgroundcolor', 'cyan'); 
popup_order = uicontrol('parent', h_options, 'style', 'popup', ...
    'unit', 'pixels', 'position', pos_1-2, 'string', {'ss3mad', 'e3'}, ...
    'fontweight', 'bold', 'value', 1, 'callback', ...
    'temp=get(gco, ''string''); v=get(gco, ''value''); ease.options_init.order_statistics=temp{v};'); 

%% candidate neurons 
pos_0(2) = pos_0(2) - h; 
pos_1(2) = pos_1(2) -h;  
text_candidate = uicontrol('parent', h_options, 'style', 'pushbutton', ...
    'unit', 'pixels', 'position', pos_0, 'string', 'candidate neurons', ...
    'fontweight', 'bold', 'backgroundcolor', 'cyan'); 
popup_candidate = uicontrol('parent', h_options, 'style', 'edit', ...
    'unit', 'pixels', 'position', pos_1-2, 'string', ...
    int2str(obj.options_init.K_candidate), ...
    'fontweight', 'bold', 'callback', ...
    'temp=get(gco, ''string''); ease.options_init.K_candidate=str2double(temp);'); 


%% new neurons  
pos_0(2) = pos_0(2) - h; 
pos_1(2) = pos_1(2) -h;  
text_new = uicontrol('parent', h_options, 'style', 'pushbutton', ...
    'unit', 'pixels', 'position', pos_0, 'string', 'neurons to add', ...
    'fontweight', 'bold', 'backgroundcolor', 'cyan'); 
popup_new = uicontrol('parent', h_options, 'style', 'edit', ...
    'unit', 'pixels', 'position', pos_1-2, 'string', ...
    int2str(obj.options_init.K_new), ...
    'fontweight', 'bold', 'callback', ...
    'temp=get(gco, ''string''); ease.options_init.K_new =str2double(temp);'); 

%% min similarity   
pos_0(2) = pos_0(2) - h; 
pos_1(2) = pos_1(2) -h;  
text_similarity= uicontrol('parent', h_options, 'style', 'pushbutton', ...
    'unit', 'pixels', 'position', pos_0, 'string', 'min similarity', ...
    'fontweight', 'bold', 'backgroundcolor', 'cyan'); 
popup_similarity = uicontrol('parent', h_options, 'style', 'edit', ...
    'unit', 'pixels', 'position', pos_1-2, 'string', ...
    num2str(obj.options_init.min_similarity), ...
    'fontweight', 'bold', 'callback', ...
    'temp=get(gco, ''string''); ease.options_init.min_similarity=str2double(temp);'); 

obj.gui.h_options = h_options; 
